"""Batch processing and parameter sweep generation."""
from __future__ import annotations

import statistics
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import streamlit as st

from planetary_eos_lab.core.config_io import save_config_json
from planetary_eos_lab.core.model_schema import OXIDE_ORDER, validate_model_entry
from planetary_eos_lab.core.pipeline_runner import full_pipeline_command
from planetary_eos_lab.core.validation_summary import (
    model_output_paths,
    read_text_if_exists,
    validation_status,
)


@dataclass
class ParameterSweep:
    """Configuration for a parameter sweep."""

    base_model: dict[str, Any]
    varied_oxide: str
    min_value: float
    max_value: float
    step: float


def generate_sweep_models(sweep: ParameterSweep) -> list[dict[str, Any]]:
    """Generate model variations for parameter sweep.

    Args:
        sweep: Parameter sweep configuration

    Returns:
        List of model dictionaries
    """
    models = []
    values = []
    value = sweep.min_value

    # Generate values (inclusive of max)
    while value <= sweep.max_value + 1e-9:  # Small epsilon for float comparison
        values.append(value)
        value += sweep.step

    for idx, value in enumerate(values):
        model = deepcopy(sweep.base_model)
        base_project = sweep.base_model.get("project", "sweep")
        model["project"] = f"{base_project}_sweep_{sweep.varied_oxide}_{idx:03d}"
        model["description"] = f"Batch sweep: {sweep.varied_oxide}={value:.2f} wt%"
        model["oxides_wt_percent"][sweep.varied_oxide] = value
        model["planetprofile_filename"] = f"{model['project']}_PerpleX.tab"
        model["source_note"] = (
            f"Generated by batch sweep. Base: {base_project}, "
            f"varied {sweep.varied_oxide} from {sweep.min_value} to {sweep.max_value} wt%"
        )
        models.append(model)

    return models


def show_batch_workspace(config_path: Path, config: dict[str, Any], models: list[dict[str, Any]]):
    """Render batch processing workspace.

    Args:
        config_path: Path to config file
        config: Configuration dictionary
        models: List of existing models
    """
    st.subheader("Batch Processing")
    st.caption("Generate multiple compositions with systematic parameter variations")

    if not models:
        st.warning("No models available. Create a base composition first in Composition > Build.")
        return

    # Select base model
    base_project = st.selectbox(
        "Base composition",
        options=[m["project"] for m in models],
        help="This composition will be used as the starting point for the sweep",
    )
    base_model = next(m for m in models if m["project"] == base_project)

    # Define sweep parameters
    st.subheader("Parameter Sweep Configuration")
    col1, col2 = st.columns(2)

    with col1:
        varied_oxide = st.selectbox(
            "Oxide to vary",
            options=list(OXIDE_ORDER),
            help="This oxide concentration will be varied systematically",
        )

        base_value = float(base_model.get("oxides_wt_percent", {}).get(varied_oxide, 0.0))

        min_value = st.number_input(
            "Min value (wt%)",
            value=max(0.0, base_value - 2.0),
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            format="%.2f",
        )

        max_value = st.number_input(
            "Max value (wt%)",
            value=min(100.0, base_value + 2.0),
            min_value=min_value,
            max_value=100.0,
            step=0.1,
            format="%.2f",
        )

        step_size = st.number_input(
            "Step size (wt%)", value=0.5, min_value=0.01, max_value=10.0, step=0.1, format="%.2f"
        )

    with col2:
        # Preview sweep
        if min_value <= max_value and step_size > 0:
            sweep = ParameterSweep(base_model, varied_oxide, min_value, max_value, step_size)
            sweep_models = generate_sweep_models(sweep)

            st.metric("Number of models", len(sweep_models))
            st.caption(f"Varying {varied_oxide} from {min_value:.2f} to {max_value:.2f} wt% in steps of {step_size:.2f}")

            # Preview in expandable
            with st.expander("📋 Preview generated models"):
                preview_data = [
                    {
                        "Project": m["project"],
                        f"{varied_oxide} (wt%)": m["oxides_wt_percent"][varied_oxide],
                        "Description": m.get("description", ""),
                    }
                    for m in sweep_models
                ]
                st.dataframe(preview_data, use_container_width=True, hide_index=True)

            # Validation check
            invalid_count = sum(1 for m in sweep_models if not validate_model_entry(m).ok)
            if invalid_count > 0:
                st.warning(f"⚠️ {invalid_count} of {len(sweep_models)} models have validation issues")

        else:
            st.error("Invalid sweep parameters")
            sweep_models = []

    # Add batch to config
    st.divider()
    if sweep_models:
        if st.button("➕ Add batch to config", type="primary", use_container_width=True):
            if "models" not in config:
                config["models"] = []

            # Check for duplicate project names
            existing_projects = {m.get("project") for m in config["models"]}
            new_models = [m for m in sweep_models if m["project"] not in existing_projects]
            duplicate_count = len(sweep_models) - len(new_models)

            config["models"].extend(new_models)
            save_config_json(config_path, config)

            if duplicate_count > 0:
                st.warning(f"⚠️ Skipped {duplicate_count} duplicate project names")
            st.success(f"✅ Added {len(new_models)} models to config")
            st.info("Switch to 'Run Pipeline' mode to execute the batch")
            st.rerun()

    # Run batch section
    st.divider()
    st.subheader("Run Generated Batch Models")

    # Find batch models (those that match the sweep pattern)
    batch_prefix = f"{base_project}_sweep_{varied_oxide}_"
    batch_models = [m for m in models if m["project"].startswith(batch_prefix)]

    if not batch_models:
        st.info(
            "No generated batch models found for this base composition and oxide. "
            "Use `Add batch to config` above first; after the config is saved, the generated variants "
            "will appear here."
        )
    else:
        st.caption(f"Found {len(batch_models)} models in this batch")

        validated = sum(
            1
            for m in batch_models
            if validation_status(read_text_if_exists(model_output_paths(m, config_path).validation_report)) == "pass"
        )
        st.caption(f"Status: {validated}/{len(batch_models)} validated")

        batch_projects = [str(model["project"]) for model in batch_models]
        projects_to_run = st.multiselect(
            "Batch models to run",
            options=batch_projects,
            default=[],
            help="Choose which generated batch variants to run through BUILD/VERTEX/WERAMI.",
        )
        if not projects_to_run:
            st.info("Select at least one batch model to run.")
        if st.button("Run selected batch model(s)", disabled=not projects_to_run, use_container_width=True):
            from planetary_eos_lab.gui.streamlit_app import relabel_command, run_streamlit_commands

            commands = [
                relabel_command(full_pipeline_command(config_path, project=project), f"Run pipeline: {project}")
                for project in projects_to_run
            ]
            run_streamlit_commands(commands)

    # Results matrix
    if batch_models:
        st.divider()
        st.subheader("Batch Results")
        show_batch_results_matrix(batch_models, config_path, varied_oxide)


def show_batch_results_matrix(models: list[dict[str, Any]], config_path: Path, varied_oxide: str):
    """Display batch results in a matrix view.

    Args:
        models: List of batch models
        config_path: Path to config file
        varied_oxide: Name of varied oxide
    """
    results = []

    for model in models:
        paths = model_output_paths(model, config_path)
        report = read_text_if_exists(paths.validation_report)
        status = validation_status(report)

        # Extract key metrics from .tab if available
        avg_rho = None
        avg_vp = None
        avg_vs = None

        if paths.planetprofile_table.exists():
            try:
                from validate_tab import column_indices, read_tab

                tab = read_tab(paths.planetprofile_table)
                indices = column_indices(tab.headers)

                if "rho_kgm3" in indices:
                    rho_values = [row[indices["rho_kgm3"]] for row in tab.rows]
                    finite_rho = [v for v in rho_values if abs(v) < 1e90]
                    if finite_rho:
                        avg_rho = statistics.mean(finite_rho)

                if "vp_kms" in indices:
                    vp_values = [row[indices["vp_kms"]] for row in tab.rows]
                    finite_vp = [v for v in vp_values if abs(v) < 1e90]
                    if finite_vp:
                        avg_vp = statistics.mean(finite_vp)

                if "vs_kms" in indices:
                    vs_values = [row[indices["vs_kms"]] for row in tab.rows]
                    finite_vs = [v for v in vs_values if abs(v) < 1e90]
                    if finite_vs:
                        avg_vs = statistics.mean(finite_vs)

            except Exception:
                pass  # Skip if parsing fails

        results.append(
            {
                "Project": model["project"],
                f"{varied_oxide} (wt%)": model["oxides_wt_percent"].get(varied_oxide, 0.0),
                "Validation": status,
                "Avg ρ (kg/m³)": f"{avg_rho:.1f}" if avg_rho else "—",
                "Avg Vp (km/s)": f"{avg_vp:.2f}" if avg_vp else "—",
                "Avg Vs (km/s)": f"{avg_vs:.2f}" if avg_vs else "—",
            }
        )

    st.dataframe(results, use_container_width=True, hide_index=True)

    # Summary statistics
    if results:
        st.caption(f"**Summary**: {len(results)} models in batch")
        passed = sum(1 for r in results if r["Validation"] == "pass")
        failed = sum(1 for r in results if r["Validation"] == "fail")
        missing = sum(1 for r in results if r["Validation"] == "missing")

        col1, col2, col3 = st.columns(3)
        col1.metric("✅ Passed", passed)
        col2.metric("❌ Failed", failed)
        col3.metric("⏳ Pending", missing)
